# Generated by Django 5.0.6 on 2024-10-07 12:22

import user_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0018_alter_customuser_trial_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trial_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='trial_end_date',
            field=models.DateTimeField(default=user_auth.models.default_trial_end_date),
        ),
    ]
