# Generated by Django 5.0.6 on 2024-08-06 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correct_option', to='questionBank.option'),
        ),
    ]
