# Generated by Django 5.0.6 on 2024-08-22 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0007_alter_question_correct_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionBank.question')),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionBank.testsession')),
            ],
            options={
                'unique_together': {('test_session', 'question')},
            },
        ),
    ]
