# Generated by Django 5.0.6 on 2024-08-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0008_testsessionquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
